# Generated by Django 5.1.5 on 2025-01-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
